[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dashboard]
command=node /app/dashboard/server.js
directory=/app/dashboard
autostart=true
autorestart=true
environment=PORT=3005,HOSTNAME="0.0.0.0",NODE_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:login]
command=node /app/login/apps/login/server.js
directory=/app/login
autostart=true
autorestart=true
environment=PORT=3000,HOSTNAME="0.0.0.0",NODE_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:accounts]
command=node /app/accounts/apps/accounts/server.js
directory=/app/accounts
autostart=true
autorestart=true
environment=PORT=3001,HOSTNAME="0.0.0.0",NODE_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:bill-payment]
command=node /app/bill-payment/apps/bill-payment/server.js
directory=/app/bill-payment
autostart=true
autorestart=true
environment=PORT=3002,HOSTNAME="0.0.0.0",NODE_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:card-management]
command=node /app/card-management/apps/card-management/server.js
directory=/app/card-management
autostart=true
autorestart=true
environment=PORT=3003,HOSTNAME="0.0.0.0",NODE_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:transactions]
command=node /app/transactions/apps/transactions/server.js
directory=/app/transactions
autostart=true
autorestart=true
environment=PORT=3004,HOSTNAME="0.0.0.0",NODE_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
